// packages/app/src/components/BrowseView.svelte
<script lang="ts">
  import { app } from '../lib/toybox.svelte.ts'
  import { formatDate } from '../lib/format.ts'

  const results = $derived(app.results())
</script>

<div class="browse">
  <div class="searchbar">
    <input
      type="search"
      placeholder="Search mods — try 'terminal', 'qemu', or fuzzy fragments like 'ptty'…"
      bind:value={app.query}
    />
    <span class="muted">{results.length} of {app.index?.mods.length ?? 0} mods</span>
  </div>

  {#if !app.index}
    <p class="muted">Loading index…</p>
  {:else}
    <div class="grid">
      {#each results as r (r.item.id)}
        {@const installed = app.installedById(r.item.id)}
        {@const latest = app.releasesFor(r.item)[0]}
        <button class="card mod" onclick={() => (app.selectedModId = r.item.id)}>
          <div class="head">
            <strong>{r.item.name}</strong>
            {#if latest}
              <span class="muted">v{latest.version}</span>
            {/if}
            {#if installed}
              {@const update = app.updateAvailable(installed)}
              {#if update}
                <span class="badge warn">update → {update}</span>
              {:else}
                <span class="badge good">installed {installed.version}</span>
              {/if}
            {/if}
            {#if app.inCart(r.item.id)}
              <span class="badge info">in cart: {app.inCart(r.item.id)}</span>
            {/if}
          </div>
          <p class="summary">{r.item.summary}</p>
          <div class="meta">
            {#each r.item.tags as tag (tag)}
              <span class="tag">{tag}</span>
            {/each}
            <span class="muted spacer">
              {r.item.authors.join(', ')}
              {#if latest?.publishedAt}
                · {formatDate(latest.publishedAt)}
              {/if}
            </span>
          </div>
        </button>
      {/each}
    </div>
    {#if results.length === 0}
      <p class="muted">No mods match “{app.query}”.</p>
    {/if}
  {/if}
</div>

<style>
  .searchbar {
    display: flex;
    align-items: center;
    gap: 14px;
    margin-bottom: 16px;
  }
  .searchbar input {
    flex: 1;
    font-size: 15px;
    padding: 9px 14px;
  }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 12px;
  }
  .mod {
    text-align: left;
    display: flex;
    flex-direction: column;
    gap: 6px;
    cursor: pointer;
  }
  .mod:hover {
    border-color: var(--accent-dim);
  }
  .head {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
  }
  .summary {
    margin: 0;
    color: var(--text-dim);
    display: -webkit-box;
    -webkit-line-clamp: 2;
    line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
  .meta {
    display: flex;
    gap: 6px;
    align-items: center;
    flex-wrap: wrap;
    font-size: 12px;
  }
  .spacer {
    margin-left: auto;
  }
</style>

// packages/app/src/components/BrowseView.tsx
import { useStore } from '@nanostores/react'
import { formatDate } from '../lib/format.ts'
import {
  $cartInstall,
  $cartRemove,
  $index,
  $installed,
  $platform,
  $query,
  $selectedModId,
  inCart,
  installedById,
  releasesFor,
  $results,
  updateAvailable,
} from '../state/appStore.ts'
import { Badge, SearchField, Tag, card } from '../ui/kit'

export function BrowseView() {
  const index = useStore($index)
  const query = useStore($query)
  const results = useStore($results)
  const installed = useStore($installed)
  const platform = useStore($platform)
  const cartInstall = useStore($cartInstall)
  const cartRemove = useStore($cartRemove)

  return (
    <div>
      <div className="mb-4 flex items-center gap-3.5">
        <SearchField
          aria-label="Search mods"
          placeholder="Search mods — try 'terminal', 'qemu', or fuzzy fragments like 'ptty'…"
          value={query}
          onChange={(v) => $query.set(v)}
        />
        <span className="hidden whitespace-nowrap text-fg-muted sm:inline">
          {results.length} of {index?.mods.length ?? 0} mods
        </span>
      </div>

      {!index ? (
        <p className="text-fg-muted">Loading index…</p>
      ) : (
        <>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-[repeat(auto-fill,minmax(320px,1fr))]">
            {results.map((r) => {
              const installedMod = installedById(installed, r.item.id)
              const latest = releasesFor(r.item, platform)[0]
              const update = installedMod ? updateAvailable(index, installedMod) : null
              const carted = inCart(cartInstall, cartRemove, r.item.id)
              return (
                <button
                  key={r.item.id}
                  type="button"
                  className={`${card} flex cursor-pointer flex-col gap-1.5 px-4 py-3.5 text-left transition-colors hover:border-accent-muted`}
                  onClick={() => $selectedModId.set(r.item.id)}
                >
                  <div className="flex flex-wrap items-center gap-2">
                    <strong>{r.item.name}</strong>
                    {latest && <span className="text-fg-muted">v{latest.version}</span>}
                    {installedMod &&
                      (update ? (
                        <Badge tone="warn">update → {update}</Badge>
                      ) : (
                        <Badge tone="good">installed {installedMod.version}</Badge>
                      ))}
                    {carted && <Badge tone="info">in cart: {carted}</Badge>}
                  </div>
                  <p className="m-0 line-clamp-2 text-fg-muted">{r.item.summary}</p>
                  <div className="flex flex-wrap items-center gap-1.5 text-xs">
                    {r.item.tags.map((tag) => (
                      <Tag key={tag}>{tag}</Tag>
                    ))}
                    <span className="ml-auto text-fg-muted">
                      {r.item.authors.join(', ')}
                      {latest?.publishedAt ? ` · ${formatDate(latest.publishedAt)}` : ''}
                    </span>
                  </div>
                </button>
              )
            })}
          </div>
          {results.length === 0 && <p className="text-fg-muted">No mods match “{query}”.</p>}
        </>
      )}
    </div>
  )
}
