// packages/app/src/components/ModDetail.tsx
import { useStore } from '@nanostores/react'
import { useEffect } from 'react'
import { X } from 'lucide-react'
import { formatBytes, formatDate } from '../lib/format.ts'
import {
  $cartInstall,
  $cartRemove,
  $index,
  $installed,
  $platform,
  $readmes,
  addInstall,
  addRemove,
  artifactRef,
  dropFromCart,
  inCart,
  installedById,
  loadReadme,
  modBrowseUrl,
  modById,
  releasesFor,
} from '../state/appStore.ts'
import { Badge, Button, Dialog, Link, Modal, Tag } from '../ui/kit'
import { Markdown } from './Markdown.tsx'

export function ModDetail({ modId, onClose }: { modId: string; onClose: () => void }) {
  const index = useStore($index)
  const installed = useStore($installed)
  const platform = useStore($platform)
  const readmes = useStore($readmes)
  const cartInstall = useStore($cartInstall)
  const cartRemove = useStore($cartRemove)

  const mod = modById(index, modId)
  const installedMod = installedById(installed, modId)
  const releases = mod ? releasesFor(mod, platform) : []
  const readme = readmes[modId]
  const browseUrl = mod ? modBrowseUrl(mod) : null
  const carted = inCart(cartInstall, cartRemove, modId)

  useEffect(() => {
    if (mod) loadReadme(mod)
  }, [mod])

  return (
    <Modal isOpen onOpenChange={(open) => !open && onClose()}>
      <Dialog aria-label={modId}>
        {!mod ? (
          <p>Unknown mod: {modId}</p>
        ) : (
          <>
            <div className="flex items-center gap-3">
              <h2 className="m-0 flex-1 text-xl font-bold">{mod.name}</h2>
              {installedMod && <Badge tone="good">installed {installedMod.version}</Badge>}
              <Button size="sm" aria-label="Close" onPress={onClose}>
                <X size={13} /> close
              </Button>
            </div>
            <p className="text-fg-muted">{mod.summary}</p>
            <div className="text-fg-muted">
              {mod.authors.join(', ')}
              {mod.license && <> · {mod.license}</>}
              {mod.repository && (
                <>
                  {' · '}
                  <Link
                    href={mod.repository}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-accent"
                  >
                    repository
                  </Link>
                </>
              )}
              {mod.homepage && (
                <>
                  {' · '}
                  <Link
                    href={mod.homepage}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-accent"
                  >
                    homepage
                  </Link>
                </>
              )}
              {' · maintained by '}
              {mod.owners.map((o) => `@${o}`).join(', ')}
              {browseUrl && (
                <>
                  {' · '}
                  <Link
                    href={browseUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-fg-muted hover:text-accent"
                  >
                    index
                  </Link>
                </>
              )}
            </div>

            <h3 className="mt-5 mb-2 font-semibold">Releases</h3>
            <div className="flex flex-col">
              {releases.map((rel) => {
                const artifact = artifactRef(rel, platform)
                return (
                  <div
                    key={rel.version}
                    className="flex flex-wrap items-center gap-x-3 gap-y-1 border-t border-border py-2"
                  >
                    <strong>{rel.version}</strong>
                    <span className="text-fg-muted">{formatDate(rel.publishedAt)}</span>
                    <span className="flex flex-wrap items-center gap-1.5">
                      {rel.channel === 'prerelease' && <Badge tone="warn">prerelease</Badge>}
                      {rel.ksa && <Tag>KSA {rel.ksa}</Tag>}
                      {rel.required.map((ref) => (
                        <Tag key={ref.id} title={ref.description ?? 'required'}>
                          ◆ {ref.id} {ref.range}
                        </Tag>
                      ))}
                      {rel.recommends.map((ref) => (
                        <Tag key={ref.id} title={ref.description ?? 'recommended'}>
                          ◇ {ref.id} {ref.range}
                        </Tag>
                      ))}
                    </span>
                    <span className="ml-auto flex items-center gap-2">
                      <span className="text-fg-muted">
                        {artifact ? formatBytes(artifact.size) : '—'}
                      </span>
                      {installedMod?.version === rel.version ? (
                        <span className="text-fg-muted">current</span>
                      ) : (
                        <Button size="sm" onPress={() => addInstall(mod.id, rel.version)}>
                          {installedMod ? 'switch to' : 'add to cart'}
                        </Button>
                      )}
                    </span>
                  </div>
                )
              })}
            </div>

            <div className="mt-3.5 flex flex-wrap gap-2.5">
              {carted ? (
                <Button onPress={() => dropFromCart(mod.id)}>Remove from cart</Button>
              ) : (
                <>
                  <Button variant="primary" onPress={() => addInstall(mod.id)}>
                    {installedMod ? 'Upgrade to latest' : 'Install latest'}
                  </Button>
                  {installedMod && (
                    <Button variant="danger" onPress={() => addRemove(mod.id)}>
                      Uninstall…
                    </Button>
                  )}
                </>
              )}
            </div>

            {mod.readmePath && (
              <>
                <hr className="my-4 border-0 border-t border-border" />
                {readme === 'loading' || readme === undefined ? (
                  <p className="text-fg-muted">Loading readme…</p>
                ) : readme === null ? (
                  <p className="text-fg-muted">The readme could not be loaded.</p>
                ) : (
                  <Markdown source={readme} />
                )}
              </>
            )}
          </>
        )}
      </Dialog>
    </Modal>
  )
}

// packages/app/src/components/ModDetail.svelte
<script lang="ts">
  import { app } from '../lib/toybox.svelte.ts'
  import { formatBytes, formatDate } from '../lib/format.ts'
  import Markdown from './Markdown.svelte'

  let { modId, onclose }: { modId: string; onclose: () => void } = $props()

  const mod = $derived(app.modById(modId))
  const installed = $derived(app.installedById(modId))
  const releases = $derived(mod ? app.releasesFor(mod) : [])
  const readme = $derived(app.readmes[modId])

  $effect(() => {
    if (mod) app.loadReadme(mod)
  })
</script>

<div
  class="overlay"
  onclick={(e) => e.target === e.currentTarget && onclose()}
  onkeydown={(e) => e.key === 'Escape' && onclose()}
  role="presentation"
>
  <div class="panel card" role="dialog" aria-label={modId}>
    {#if !mod}
      <p>Unknown mod: {modId}</p>
    {:else}
      <div class="head">
        <h2>{mod.name}</h2>
        {#if installed}
          <span class="badge good">installed {installed.version}</span>
        {/if}
        <button class="small close" onclick={onclose}>✕ close</button>
      </div>
      <p class="muted">{mod.summary}</p>
      <div class="links muted">
        {mod.authors.join(', ')}
        {#if mod.license}· {mod.license}{/if}
        {#if mod.repository}
          · <a href={mod.repository} target="_blank" rel="noopener noreferrer">repository</a>
        {/if}
        {#if mod.homepage}
          · <a href={mod.homepage} target="_blank" rel="noopener noreferrer">homepage</a>
        {/if}
        · maintained by {mod.owners.map((o) => `@${o}`).join(', ')}
        {#if app.modBrowseUrl(mod)}
          · <a class="quiet" href={app.modBrowseUrl(mod)} target="_blank" rel="noopener noreferrer"
            >index</a>
        {/if}
      </div>

      <h3>Releases</h3>
      <table class="releases">
        <tbody>
          {#each releases as rel (rel.version)}
            {@const artifact = app.artifactRef(rel)}
            <tr>
              <td><strong>{rel.version}</strong></td>
              <td class="muted">{formatDate(rel.publishedAt)}</td>
              <td>
                {#if rel.channel === 'prerelease'}<span class="badge warn">prerelease</span>{/if}
                {#if rel.ksa}<span class="tag">KSA {rel.ksa}</span>{/if}
                {#each rel.required as ref (ref.id)}
                  <span class="tag" title={ref.description ?? 'required'}>
                    ◆ {ref.id} {ref.range}
                  </span>
                {/each}
                {#each rel.recommends as ref (ref.id)}
                  <span class="tag" title={ref.description ?? 'recommended'}>
                    ◇ {ref.id} {ref.range}
                  </span>
                {/each}
              </td>
              <td class="muted">{artifact ? formatBytes(artifact.size) : '—'}</td>
              <td>
                {#if installed?.version === rel.version}
                  <span class="muted">current</span>
                {:else}
                  <button
                    class="small"
                    onclick={() => app.addInstall(mod.id, rel.version)}
                  >
                    {installed ? 'switch to' : 'add to cart'}
                  </button>
                {/if}
              </td>
            </tr>
          {/each}
        </tbody>
      </table>

      <div class="actions">
        {#if app.inCart(mod.id)}
          <button onclick={() => app.drop(mod.id)}>Remove from cart</button>
        {:else}
          <button class="primary" onclick={() => app.addInstall(mod.id)}>
            {installed ? 'Upgrade to latest' : 'Install latest'}
          </button>
          {#if installed}
            <button class="danger" onclick={() => app.addRemove(mod.id)}>Uninstall…</button>
          {/if}
        {/if}
      </div>

      {#if mod.readmePath}
        <hr />
        {#if readme === 'loading' || readme === undefined}
          <p class="muted">Loading readme…</p>
        {:else if readme === null}
          <p class="muted">The readme could not be loaded.</p>
        {:else}
          <Markdown source={readme} />
        {/if}
      {/if}
    {/if}
  </div>
</div>

<style>
  .overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.55);
    display: grid;
    place-items: start center;
    padding: 40px 20px;
    overflow-y: auto;
    z-index: 10;
  }
  .panel {
    max-width: 760px;
    width: 100%;
    padding: 22px 26px;
  }
  .head {
    display: flex;
    align-items: center;
    gap: 12px;
  }
  .head h2 {
    margin: 0;
    flex: 1;
  }
  .links a {
    color: var(--accent);
  }
  .links a.quiet {
    color: var(--text-dim);
  }
  .links a.quiet:hover {
    color: var(--accent);
  }
  .releases {
    width: 100%;
    border-collapse: collapse;
  }
  .releases td {
    padding: 6px 8px;
    border-top: 1px solid var(--border);
    vertical-align: top;
  }
  .actions {
    display: flex;
    gap: 10px;
    margin-top: 14px;
  }
  hr {
    border: none;
    border-top: 1px solid var(--border);
    margin: 18px 0;
  }
</style>
