// packages/app/src/components/ThemeToggle.svelte
<script lang="ts">
  import { theme } from '../lib/theme.svelte.ts'

  const label = $derived(
    theme.preference === 'system' ? '🌓 auto' : theme.preference === 'light' ? '☀️ light' : '🌙 dark',
  )
  const title = $derived(
    theme.preference === 'system'
      ? `Theme: following your system (${theme.effective}) — click to force light`
      : theme.preference === 'light'
        ? 'Theme: forced light — click to force dark'
        : 'Theme: forced dark — click to follow your system',
  )
</script>

<button class="small theme-toggle" {title} aria-label="Toggle color theme" onclick={() => theme.cycle()}>
  {label}
</button>

<style>
  .theme-toggle {
    white-space: nowrap;
  }
</style>

// packages/app/src/components/ThemeToggle.tsx
import { useStore } from '@nanostores/react'
import { Moon, SunMedium, SunMoon } from 'lucide-react'
import { Button } from '../ui/kit'
import { $effectiveTheme, $themePreference, cycleTheme } from '../state/theme.ts'

export function ThemeToggle() {
  const preference = useStore($themePreference)
  const effective = useStore($effectiveTheme)

  const title =
    preference === 'system'
      ? `Theme: following your system (${effective}) — click to force light`
      : preference === 'light'
        ? 'Theme: forced light — click to force dark'
        : 'Theme: forced dark — click to follow your system'

  return (
    <Button size="sm" variant="ghost" aria-label="Toggle color theme" onPress={cycleTheme}>
      {preference === 'system' ? (
        <SunMoon size={14} />
      ) : preference === 'light' ? (
        <SunMedium size={14} />
      ) : (
        <Moon size={14} />
      )}
      <span title={title}>{preference === 'system' ? 'auto' : preference}</span>
    </Button>
  )
}
